### ISSUE TITLE
Propose updating to Mattermost 3.5

### ISSUE THREAD

**Issue by jasonblais** [cloudfoundry-community/mattermost-cf-integrator#3]
Hey @ArthurHlt and others,

Just wanted to inform you that Mattermost 3.5 release has been cut.

The new release contains security updates and several API changes - you can [view the full changelog for Mattermost 3.5 here](https://docs.mattermost.com/administration/changelog.html#release-v3-5-0) and [find download links with hash numbers here](https://pre-release.mattermost.com/core/pl/9ye3kypwpfdqdyxxh9wwqc9qpe)

Wondering if you'd like to help update the Cloud Foundry Installer to be compatible with Mattermost 3.5?

If you do update, please consider tweeting about it, which we can then retweet for greater reach.

Also, feel free to join the [Mattermost Installers community channel](https://pre-release.mattermost.com/core/channels/installers-and-images) for latest news relevant for installer owners.

**Comment by ArthurHlt** [comment]
Hello @jasonblais ,

We now have the latest version of mattermost available here 

We have an automatic pipeline to update to the next here it was broken, I will consider to tweet in the same time. Thank you for your advice

**Comment by jasonblais** [comment]
Many thanks @ArthurHlt!
