### ISSUE TITLE
Mattermost 3.6.2

### ISSUE THREAD

**Issue by jasonblais** [cloudfoundry-community/mattermost-cf-integrator#4]
Hey @ArthurHlt,

just checking that the automated updates to take the latest Mattermost release was successful?

Would there be a place this can be confirmed?

Mattermost 3.6.2 includes a high severity security issue and upgrading is recommended. Blog post here with details: https://about.mattermost.com/mattermost-3-6-2/.

If you'd like to stay informed about new security updates to Mattermost, you can sign in to our [Security Bulletin mailing list](http://eepurl.com/cAl5Rv). This mailing list will receive an email about a new security release so that installers can update to that version.

**Comment by ArthurHlt** [comment]
Hello @jasonblais thank you for the reminder , it seems that my pipeline didn't do its work. I will fix it.
I've triggered the release manually.
